export const ADD_BOOKS = "ADD_BOOKS";
export const REMOVE_SELECTED_BOOK = "REMOVE_SELECTED_BOOK";
export const REMOVE_ALL = "REMOVE_ALL";

export const FETCH_BOOKS_LOADING = "FETCH_BOOKS_LOADING";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_ERROR = "FETCH_BOOKS_ERROR";
